### ISSUE TITLE
java Exception with Fitnesse 20210606

### ISSUE THREAD

**Issue by RouxThomas** [sbellus/fitnesse-plantuml-plugin#2]
Hello,
i 'm using Fitnesse 20210606 and i try to use the plantUml plugin, but without success.

my java version :
$ java -version
java version "1.8.0_281"

my dot version :
$ dot -version
dot - graphviz version 2.47.1 (20210417.1919)

my page content :
!startuml
class myClass
!enduml

The call stack :
WARNING: Unexpected exception [fitnesse.wikitext.parser.Parser.getVariableSource()Lfitnesse/wikitext/parser/VariableSource;]
java.lang.NoSuchMethodError: fitnesse.wikitext.parser.Parser.getVariableSource()Lfitnesse/wikitext/parser/VariableSource;
        at com.github.sbellus.fitnesse.plantuml.graphics.GraphicsSymbol.parse(GraphicsSymbol.java:32)
        at fitnesse.wikitext.parser.ParseSpecification.parseSymbol(ParseSpecification.java:118)
        at fitnesse.wikitext.parser.ParseSpecification.parse(ParseSpecification.java:88)
        at fitnesse.wikitext.parser.Parser.parse(Parser.java:144)
        at fitnesse.wikitext.parser.SyntaxTreeV2.parse(SyntaxTreeV2.java:26)
        at fitnesse.wikitext.parser.MarkUpSystemV2.parse(MarkUpSystemV2.java:16)
        at fitnesse.wiki.BaseWikitextPage.parse(BaseWikitextPage.java:62)
        at fitnesse.wiki.BaseWikitextPage.getHtml(BaseWikitextPage.java:49)
        at fitnesse.wiki.WikiPageUtil.makePageHtml(WikiPageUtil.java:65)
        at fitnesse.responders.WikiPageResponder$WikiPageRenderer.render(WikiPageResponder.java:125)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:571)
        at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:554)
        at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:221)
        at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:368)
        at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:492)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
        at org.apache.velocity.runtime.directive.Parse.render(Parse.java:284)
        at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:304)
        at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:439)
        at org.apache.velocity.Template.merge(Template.java:358)
        at org.apache.velocity.Template.merge(Template.java:262)
        at fitnesse.html.template.HtmlPage.render(HtmlPage.java:83)
        at fitnesse.html.template.HtmlPage.html(HtmlPage.java:76)
        at fitnesse.responders.WikiPageResponder.makeHtml(WikiPageResponder.java:105)
        at fitnesse.responders.WikiPageResponder.makePageResponse(WikiPageResponder.java:67)
        at fitnesse.responders.WikiPageResponder.makeResponse(WikiPageResponder.java:40)
        at fitnesse.FitNesseExpediter.createGoodResponse(FitNesseExpediter.java:145)
        at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:112)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Thanks for your help !

**Comment by sbellus** [comment]
Hi

I do not use FitNesse for long time and I do not actively maintain this
plugin. Probably I will find time to check it out after the summer.
Feel free to update the plugin to new FitNesse version.

**Comment by RouxThomas** [comment]
Hi, 
thank you for your reply.
I hope you will have enough time to update it, because your plugins is cool ^^.

**Comment by RouxThomas** [comment]
Hi,
I thinks i have solved the problem.
But i can't push to perform a pull request...
Can you give me the rights please ?
thank you !

**Comment by sbellus** [comment]
I added you as collaborator. Thanks for fix.

**Comment by RouxThomas** [comment]
I'm sorry, but i can't...

my logs :

thomas@thomas-linux ~/vues/fitnesse-plantuml-plugin2 (master)
$ git pull -v
From github.com:sbellus/fitnesse-plantuml-plugin
 = [up to date]      master     -> origin/master
Already up to date.
thomas@thomas-linux ~/vues/fitnesse-plantuml-plugin2 (master)
$ git checkout update_according_to_fitnesse_20210606
Switched to branch 'update_according_to_fitnesse_20210606'
thomas@thomas-linux ~/vues/fitnesse-plantuml-plugin2 (update_according_to_fitnesse_20210606)
$ git push --set-upstream origin update_according_to_fitnesse_20210606
ERROR: Permission to sbellus/fitnesse-plantuml-plugin.git denied to RouxThomas.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
thomas@thomas-linux ~/vues/fitnesse-plantuml-plugin2 (update_according_to_fitnesse_20210606)

**Comment by sbellus** [comment]
May be you should accept invite?

![Screenshot_20210824-230347_Chrome](https://user-images.githubusercontent.com/436473/130689879-52e74e22-3198-42fc-ad7d-e4493af468ea.jpg)

**Comment by RouxThomas** [comment]
Of course !
sorry...my bad...
You can now check the pull request :-)

**Comment by sbellus** [comment]
Thanks for fix. Pull request is merged.
